version: '3.6'
services:
  mongodb:
    image: mongo:3.6.8
    networks:
      - hf-net

  hf-server:
    image: nomadcr/bfx-hf-server:1.0.4
    networks:
      - hf-net
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - PLATFORM
      - API_KEY
      - API_SECRET
      - DEBUG=*
      - MONGODB_URL=mongodb://mongodb/hf-as
      - SERVER_PORT

networks:
  hf-net:

